apiVersion: v1
kind: Pod
metadata:
  name: envvars-multiple-secrets
spec:
  containers:
    - name: envars-test-container
      image: nginx
      env:
        - name: BACKEND_USERNAME
          valueFrom:
            secretKeyRef:
              key: backend-username
              name: backend-user
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: db-username
              name: db-user